[RFC][UN-6686] Create an ember cli command to generate translations
uniplaces/translations pull request #1
Opened 2016-11-08 14:48 UTC by raffo0707

https://uniplaces.atlassian.net/browse/UN-6686

2016-11-08 17:30 UTC, montoias requested changes
remove also .gitkeep

2016-11-08 17:30 UTC, montoias commented on .editorconfig
> +
remove new line

2016-11-08 17:30 UTC, montoias commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
What is this?

2016-11-08 17:30 UTC, montoias commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
remove all .idea ugly, scaffolded, auto-generated files :)

2016-11-08 17:30 UTC, montoias commented on lib/commands/get.js
> +    var self = this;
use _.bind

extract 

```
function(res, rej) {
 +      return tab.getRows({offset: 0, limit: tab.rowCount}, function(err, rows) {
 +        if (err) return rej(err);
 +
 +        var translations = self._initTranslations(self.locales, rows);
 +
 +        self._save(translations);
 +
 +        return res(rows);
 +      });
 +    }
```

to a function and do

_.bind(this, this.functionName)

2016-11-08 17:30 UTC, montoias commented on lib/commands/get.js
> +    console.log('get translations');
keep doing it :)

2016-11-08 17:30 UTC, montoias commented on lib/commands/set.js
> +    var self = this;
same

2016-11-08 17:30 UTC, montoias commented on lib/commands/set.js
> +    return defaultLocale === locale
one line

2016-11-08 17:30 UTC, montoias commented on lib/commands/set.js
> +    var self = this;
same

2016-11-08 17:30 UTC, montoias commented on lib/commands/set.js
> +    var self = this;
same

2016-11-08 17:30 UTC, montoias commented on lib/commands/set.js
> +    var tabSelector = new TabSelector({project: this.project, tabName: options.tab});
if you move  _ember-cli-babel_ in _package.json_ from devDeps to deps, you should have access to all ECMA6 features.

including binds for free with arrow functions.

2016-11-09 11:59 UTC, montoias requested changes
remove .gitkeep

2016-11-09 11:59 UTC, montoias commented on .travis.yml
> +---
you can remove this

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +      config.locales.map((item) => { this.locales[item] = {} });
(item) to item

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +    rows.map((row) => {
(row) to row

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +      Object.keys(locales).map((key) => {
shouldn't this have a return?

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +      Object.keys(locales).map((key) => {
remove the (key)

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +        translations[key][row[this.keyCol]] = row[key];
make consts out of this, very unreadable :)

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +    for (const locale of Object.keys(translations)) {
Object.keys(translations).forEach(locale => x)

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +    let tabSelector = new TabSelector(
one line

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +    let tabHandler = tabSelector.run().then((tab) => {
you don't need to return when it's a single line.

you can do

tabSelector.run().then(tab => this._rows(tab));

you can even do something like:

tabSelector.run().then(this._rows);

2016-11-09 11:59 UTC, montoias commented on lib/commands/get.js
> +    return tabHandler.then((header) => { return header; });
return tabHandler;

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +        throw new SilentError(
one line

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +      row[`status${locale}`] = this._status(options.default, locale);
return row;

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +    return row;
remove this

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +    this.locales.map((locale) => {
return this.locales....

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +    let tabHandler = tabSelector.run().then((tab) => {
(tab) to tab

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +    return tabHandler.then((header) => {return header;});
return tabHandler

2016-11-09 11:59 UTC, montoias commented on lib/commands/set.js
> +        if (err) return rej(err);
return tab.addRow(row, (err, result) => !err ? res(result) : rej(err));

2016-11-09 11:59 UTC, montoias commented on lib/tasks/authenticate.js
> +    let authentication = readConfig.run().then((config) => {
config

2016-11-09 11:59 UTC, montoias commented on lib/tasks/authenticate.js
> +      return new Promise((res) => {
res

2016-11-09 11:59 UTC, montoias commented on lib/tasks/authenticate.js
> +    return authentication.then((spreadsheet) => {return spreadsheet;});
return authentication

2016-11-09 11:59 UTC, montoias commented on lib/tasks/read-config.js
> +      this._super.init.apply(this, arguments);
this._super.init(...arguments)

2016-11-09 11:59 UTC, montoias commented on lib/tasks/read-config.js
> +      throw new SilentError(
one line

2016-11-09 11:59 UTC, montoias commented on lib/tasks/read-config.js
> +    superConfig._result.credentials = require(
return

2016-11-09 11:59 UTC, montoias commented on lib/tasks/read-config.js
> +    return superConfig
remove

2016-11-09 11:59 UTC, montoias commented on lib/tasks/select-tab.js
> +    return tabHandler.then((tab) => {return tab;});
return tabHandler

2016-11-09 11:59 UTC, montoias commented on lib/tasks/select-tab.js
> +    let tabHandler = authentication.run().then((spreadsheet) => {
spreadsheet

2016-11-09 11:59 UTC, montoias commented on lib/tasks/select-tab.js
> +          return res(tab[0])});
this can never go wrong? 👀

2016-11-09 11:59 UTC, montoias commented on lib/utils/filesystem.js
> +  dirSync: function (filepath, permissions) {
permissions = 0777

2016-11-09 11:59 UTC, montoias commented on lib/utils/filesystem.js
> +    if (!permissions) {
remove this

2016-11-09 11:59 UTC, montoias commented on lib/utils/filesystem.js
> +  dirSync: function (filepath, permissions) {
also create a constant

2016-11-09 14:31 UTC, raffo0707 commented on .editorconfig
> +
👍

2016-11-09 16:39 UTC, satcin approved these changes

2016-11-09 16:40 UTC, montoias approved these changes

2016-11-10 17:36 UTC, merged