[WIP][NI] Update ember version and upgrade to its own environment
uniplaces/translations pull request #4
Opened 2017-03-27 15:36 UTC by AndreJoaquim

NI

2017-03-29 15:54 UTC, raffo0707 requested changes

2017-03-29 15:54 UTC, raffo0707 commented on config/environment.js
> +  var ENV = {};
why two steps?

2017-03-29 15:54 UTC, raffo0707 commented on lib/tasks/read-config.js
> +      throw new Error(`The parent config directory was not found.`)
not concatenating anything, you can use single quote: ` => '

2017-03-29 15:54 UTC, raffo0707 commented on lib/tasks/read-config.js
> +        throw new Error(`There is no such credentials file.`)
same

2017-03-29 15:54 UTC, raffo0707 commented on lib/commands/get.js
> +      if (!locales.length <= 0) {
empty line after let

2017-03-29 15:54 UTC, raffo0707 commented on lib/commands/get.js
> +        this._save(translations);
empty line after let

2017-03-29 15:54 UTC, raffo0707 commented on lib/commands/set.js
> +      if (!locales.length <= 0) {
empty line after let

2017-03-29 15:54 UTC, raffo0707 commented on lib/commands/get.js
> +let Promise = require('ember-cli/lib/ext/promise');
I know was me that did the error first. But doing the salesforce integration I learned that what get from the require should be const and not let. would you mind to change it please? thanks 🙏

2017-03-29 15:54 UTC, raffo0707 commented on lib/tasks/read-config.js
> +    if (!existsSync(path)) {
empty line after let

2017-03-30 14:54 UTC, AndreJoaquim commented on config/environment.js
> +  var ENV = {};
While this was not necessary, it allows to reproduce better a default ember app code-styling (e.g. [environment.js](https://github.com/uniplaces/self-service-frontend/blob/dev/config/environment.js) in the self-service platform).

2017-03-30 14:55 UTC, AndreJoaquim commented on lib/commands/get.js
> +let Promise = require('ember-cli/lib/ext/promise');
Of course :)

2017-03-30 15:02 UTC, raffo0707 commented on config/environment.js
> +  var ENV = {};
top :) thanks for replying

2017-03-30 15:02 UTC, raffo0707 approved these changes

2017-03-30 15:02 UTC, merged